/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\15648\\Desktop\\ZZULIOJ\\technologyStack\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-629462a1",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-629462a1").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-da88f5b2",
    path: "/top/debug/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-da88f5b2").then(next)
    },
  },
  {
    path: "/top/debug/index.html",
    redirect: "/top/debug/"
  },
  {
    name: "v-687e80de",
    path: "/top/uniapp/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-687e80de").then(next)
    },
  },
  {
    path: "/top/uniapp/index.html",
    redirect: "/top/uniapp/"
  },
  {
    name: "v-7482f09e",
    path: "/top/tool/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7482f09e").then(next)
    },
  },
  {
    path: "/top/tool/index.html",
    redirect: "/top/tool/"
  },
  {
    name: "v-51afcd01",
    path: "/top/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-51afcd01").then(next)
    },
  },
  {
    path: "/top/vue/index.html",
    redirect: "/top/vue/"
  },
  {
    name: "v-1ff68371",
    path: "/top/es/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1ff68371").then(next)
    },
  },
  {
    path: "/top/es/index.html",
    redirect: "/top/es/"
  },
  {
    name: "v-4a091992",
    path: "/top/vue/component/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4a091992").then(next)
    },
  },
  {
    path: "/top/vue/component/index.html",
    redirect: "/top/vue/component/"
  },
  {
    name: "v-17f326d8",
    path: "/top/vue/api/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-17f326d8").then(next)
    },
  },
  {
    path: "/top/vue/api/index.html",
    redirect: "/top/vue/api/"
  },
  {
    name: "v-0e9099be",
    path: "/top/vue/module/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0e9099be").then(next)
    },
  },
  {
    path: "/top/vue/module/index.html",
    redirect: "/top/vue/module/"
  },
  {
    name: "v-07200b06",
    path: "/top/vue/packaging/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-07200b06").then(next)
    },
  },
  {
    path: "/top/vue/packaging/index.html",
    redirect: "/top/vue/packaging/"
  },
  {
    name: "v-15083597",
    path: "/zh/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15083597").then(next)
    },
  },
  {
    path: "/zh/guide/index.html",
    redirect: "/zh/guide/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]