/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Technologystack",
  "description": "CC的技术栈",
  "base": "./",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "./logo.jpg"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/logo.jpg",
        "actionText": "快速预览 →",
        "actionLink": "/zh/guide/"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-629462a1",
      "path": "/"
    },
    {
      "title": "DebugFragment",
      "frontmatter": {},
      "regularPath": "/top/debug/",
      "relativePath": "top/debug/README.md",
      "key": "v-da88f5b2",
      "path": "/top/debug/",
      "headers": [
        {
          "level": 2,
          "title": "ESlint+Prettier各项配置冲突的语法报错",
          "slug": "eslint-prettier各项配置冲突的语法报错"
        },
        {
          "level": 3,
          "title": "1.修改Prettier默认配置,格式化无法生效",
          "slug": "_1-修改prettier默认配置-格式化无法生效"
        },
        {
          "level": 3,
          "title": "解决方法：",
          "slug": "解决方法"
        },
        {
          "level": 3,
          "title": "2.Prettier缺少配置，函数名和后面的括号之间加个空格",
          "slug": "_2-prettier缺少配置-函数名和后面的括号之间加个空格"
        },
        {
          "level": 3,
          "title": "3.settings.json配置项分享",
          "slug": "_3-settings-json配置项分享"
        },
        {
          "level": 2,
          "title": "error ‘XXXXX‘ is not defined no-undef",
          "slug": "error-xxxxx-is-not-defined-no-undef"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/top/uniapp/",
      "relativePath": "top/uniapp/README.md",
      "key": "v-687e80de",
      "path": "/top/uniapp/"
    },
    {
      "title": "vue持久化",
      "frontmatter": {},
      "regularPath": "/top/tool/",
      "relativePath": "top/tool/README.md",
      "key": "v-7482f09e",
      "path": "/top/tool/",
      "headers": [
        {
          "level": 2,
          "title": "vue持久化",
          "slug": "vue持久化"
        },
        {
          "level": 2,
          "title": "less的自动化导入",
          "slug": "less的自动化导入"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/top/vue/",
      "relativePath": "top/vue/README.md",
      "key": "v-51afcd01",
      "path": "/top/vue/"
    },
    {
      "title": "Array",
      "frontmatter": {},
      "regularPath": "/top/es/",
      "relativePath": "top/es/README.md",
      "key": "v-1ff68371",
      "path": "/top/es/",
      "headers": [
        {
          "level": 3,
          "title": "Array.prototype.find()",
          "slug": "array-prototype-find"
        },
        {
          "level": 3,
          "title": "Array.prototype.findIndex()",
          "slug": "array-prototype-findindex"
        },
        {
          "level": 3,
          "title": "Array.prototype.indexOf()",
          "slug": "array-prototype-indexof"
        },
        {
          "level": 3,
          "title": "Array.prototype.join()",
          "slug": "array-prototype-join"
        },
        {
          "level": 3,
          "title": "Array.prototype.map()",
          "slug": "array-prototype-map"
        },
        {
          "level": 3,
          "title": "Array.prototype.reduce()",
          "slug": "array-prototype-reduce"
        }
      ]
    },
    {
      "title": "组件传参",
      "frontmatter": {},
      "regularPath": "/top/vue/component/",
      "relativePath": "top/vue/component/README.md",
      "key": "v-4a091992",
      "path": "/top/vue/component/",
      "headers": [
        {
          "level": 2,
          "title": "父传子",
          "slug": "父传子"
        },
        {
          "level": 3,
          "title": "父组件",
          "slug": "父组件"
        },
        {
          "level": 3,
          "title": "子组件",
          "slug": "子组件"
        },
        {
          "level": 2,
          "title": "子传父",
          "slug": "子传父"
        },
        {
          "level": 2,
          "title": "provide和inject",
          "slug": "provide和inject"
        }
      ]
    },
    {
      "title": "组合API",
      "frontmatter": {},
      "regularPath": "/top/vue/api/",
      "relativePath": "top/vue/api/README.md",
      "key": "v-17f326d8",
      "path": "/top/vue/api/",
      "headers": [
        {
          "level": 2,
          "title": "setup()",
          "slug": "setup"
        },
        {
          "level": 3,
          "title": "访问 Props#",
          "slug": "访问-props"
        },
        {
          "level": 3,
          "title": "Setup 上下文",
          "slug": "setup-上下文"
        },
        {
          "level": 2,
          "title": "1-组合API-父子通讯",
          "slug": "_1-组合api-父子通讯"
        },
        {
          "level": 3,
          "title": "父传子",
          "slug": "父传子"
        },
        {
          "level": 3,
          "title": "子传父",
          "slug": "子传父"
        },
        {
          "level": 3,
          "title": "总结",
          "slug": "总结"
        },
        {
          "level": 2,
          "title": "2-组合API-依赖注入",
          "slug": "_2-组合api-依赖注入"
        },
        {
          "level": 3,
          "title": "总结：",
          "slug": "总结-2"
        },
        {
          "level": 3,
          "title": "补充：",
          "slug": "补充"
        },
        {
          "level": 2,
          "title": "3-补充-v-model语法糖",
          "slug": "_3-补充-v-model语法糖"
        },
        {
          "level": 3,
          "title": "总结：",
          "slug": "总结-3"
        },
        {
          "level": 3,
          "title": "补充：",
          "slug": "补充-2"
        },
        {
          "level": 2,
          "title": "4-补充-mixins语法",
          "slug": "_4-补充-mixins语法"
        },
        {
          "level": 3,
          "title": "总结：",
          "slug": "总结-4"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/top/vue/module/",
      "relativePath": "top/vue/module/README.md",
      "key": "v-0e9099be",
      "path": "/top/vue/module/",
      "headers": [
        {
          "level": 2,
          "title": "vuex基础",
          "slug": "vuex基础"
        },
        {
          "level": 2,
          "title": "vuex-持久化",
          "slug": "vuex-持久化"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/top/vue/packaging/",
      "relativePath": "top/vue/packaging/README.md",
      "key": "v-07200b06",
      "path": "/top/vue/packaging/"
    },
    {
      "title": "面经",
      "frontmatter": {},
      "regularPath": "/zh/guide/",
      "relativePath": "zh/guide/README.md",
      "key": "v-15083597",
      "path": "/zh/guide/",
      "headers": [
        {
          "level": 2,
          "title": "面经",
          "slug": "面经"
        },
        {
          "level": 3,
          "title": "Vue2.x 生命周期",
          "slug": "vue2-x-生命周期"
        }
      ]
    }
  ],
  "themeConfig": {
    "logo": "/logo.jpg",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "ECMAScript",
        "link": "/top/es/"
      },
      {
        "text": "Vue",
        "items": [
          {
            "items": [
              {
                "text": "组合式API",
                "link": "/top/vue/api/"
              },
              {
                "text": "module",
                "link": "/top/vue/module/"
              },
              {
                "text": "packaging",
                "link": "/top/vue/packaging/"
              },
              {
                "text": "component",
                "link": "/top/vue/component/"
              }
            ]
          }
        ]
      },
      {
        "text": "Uniapp",
        "link": "/top/uniapp/"
      },
      {
        "text": "Tool",
        "link": "/top/tool/"
      },
      {
        "text": "DebugFragment",
        "link": "/top/debug/"
      }
    ],
    "sidebarDepth": 0,
    "sidebar": "auto"
  }
}